name: Android CI

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:
  android:
    name: android
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Lint
      run: ./gradlew lintDebug

    - name: Unit Test
      if: success()
      run: ./gradlew testDebugUnitTest  --no-daemon --max-workers 2

    - name: Build with Gradle
      if: success()
      run: ./gradlew assembleDebug