name: Android CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous job
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          ignore_sha: true

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Lint
        run: ./gradlew lintDebug

      - name: Build with Gradle
        if: success()
        run: ./gradlew assembleDebug
