name: Android CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous job
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          ignore_sha: true

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Lint
        run: ./gradlew lintDebug

      - name: Unit Test
        if: success()
        run: ./gradlew testDebugUnitTest  --no-daemon --max-workers 2

      - name: Build with Gradle
        if: success()
        run: ./gradlew assembleDebug