name: Build and Deploy
on:
  push:
    branches:
      - docs-src
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Git Headers
        run: |
          git config --global url."https://api:${{ secrets.GITHUB_ACTIONS_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://ssh:${{ secrets.GITHUB_ACTIONS_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://git:${{ secrets.GITHUB_ACTIONS_TOKEN }}@github.com/".insteadOf "git@github.com:"

      - name: Build Docs
        run: |
          npm build

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: .vuepress/dist # The folder the action should deploy.
