name: Build and Deploy
on:
  push:
    branches:
      - docs-src
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # - name: Git Headers
      #   run: |
      #     git config --global url."https://api:${{ secrets.GITHUB_ACTIONS_TOKEN }}@github.com/".insteadOf "https://github.com/"
      #     git config --global url."https://ssh:${{ secrets.GITHUB_ACTIONS_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"
      #     git config --global url."https://git:${{ secrets.GITHUB_ACTIONS_TOKEN }}@github.com/".insteadOf "git@github.com:"

      - name: Build Docs
        run: |
          npm install
          npm run-script build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          # ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./.vuepress/dist
