name: Build and Deploy
on:
  push:
    branches:
      - docs-src
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Git Headers
        run: |
          git config --global url."https://api:${{ secrets.GITHUB_ACTIONS_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://ssh:${{ secrets.GITHUB_ACTIONS_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://git:${{ secrets.GITHUB_ACTIONS_TOKEN }}@github.com/".insteadOf "git@github.com:"

      - name: Build and Deploy
        uses: testthedocs/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: .vuepress/dist/ # The folder, the action should deploy.
          BUILD_SCRIPT: npm install && npm run-script build # The build script the action should run prior to deploying.
