name: Package Publish CI

on:
  push:
    branches:
      - master

env:
  READ_ARTIFACTS_TOKEN: ${{ secrets.READ_ARTIFACTS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous job
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          ignore_sha: true

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ARTIFACT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ARTIFACT_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup env
        run: |
          source version.properties
          version=$(echo $VERSION_NAME)
          echo "VERSION_NAME=$version" >> $GITHUB_ENV

          aar_file="sushilib/build/outputs/aar/sushilib-release.aar"
          file_name="sushi-v$version"

          echo "AAR_PATH=$aar_file" >> $GITHUB_ENV
          echo "FILE_NAME=$file_name" >> $GITHUB_ENV

          CODEARTIFACT_AUTH_TOKEN="$(aws codeartifact get-authorization-token --domain zartifacts --domain-owner ***REMOVED*** --query authorizationToken --duration-seconds 1800 --output text)"
          echo "::add-mask::$CODEARTIFACT_AUTH_TOKEN"
          echo "CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> $GITHUB_ENV

      - name: Build with Gradle
        run: |
          ./gradlew sushilib:assembleRelease
          ./gradlew sushilib:assembleExternal

      - name: Publish the new package
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew sushilib:publish

      - name: Release library
        if: success()
        uses: Zomato/treeware@master
        with:
          prod_branch: dev
          should_release: true
          drafter_path: .github/release-template.yml
          assets: ${{ env.AAR_PATH }}#${{ env.FILE_NAME }}
          version_name: ${{ env.VERSION_NAME }}

      - name: Master branch syncup PR
        uses: Zomato/android-lib-release-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_branch: dev
          main_branch: master
          version_file_path: version.properties
          create_sync_pr: true